export const restaurantData = [
  {
    id: 1,
    name: "Bold Butchery",
    image: "",
    cuisine: "middle-eastern",
    rating: 4,
    price: "price2",
    dietary: ["halal"],
    website: "https://www.boldshawarma.com",
    description: "Straightforward restaurant preparing shawarma & falafel wraps, plus burgers & poutine.",
  },
  {
    id: 2,
    name: "Rebar",
    image: "",
    cuisine: "american",
    rating: 4,
    price: "price2",
    dietary: ["vegetarian"],
    website: "https://www.rebarfoods.com",
    description: "Rebar is a pioneering West Coast institution that has evolved from humble beginnings into a vibrant, unique dining destination known for its nourishing, health-supporting, and eclectically creative fresh food, engaging all senses from the moment you enter.",
  },
  {
    id: 3,
    name: "La Taquisa",
    image: "",
    cuisine: "mexican",
    rating: 4,
    price: "price1",
    dietary: ["peanuts", "vegan", "vegetarian"],
    website: "https://www.lataquisa.com/locations/downtown/menu/",
    description: "La Taquisa is a locally owned, family-run business combining authentic Guadalajara family recipes from Sindy with Scott's 22 years of culinary experience to offer an exceptional Mexican dining experience featuring made-from-scratch fillings, salsas, and fresh, pressed-to-order gluten-free corn tortillas.",
  },
  {
    id: 4,
    name: "MaiiZ Nixtamal Eatery & Tortilleria",
    image: "",
    cuisine: "mexican",
    rating: 5,
    price: "price2",
    dietary: ["celiac"],
    website: "https://maiiz.ca",
    description: "MAiiZ Nixtamal is a restaurant committed to providing honest, transparent food, prioritizing local farmers and organic BC-grown corn in their mission to make nixtamalized corn products more accessible. They strive for sustainability, reduce environmental impact through local sourcing, and aim to grow as a purpose-driven business while educating the community on the nutritional and cultural importance of nixtamalization.",
  },
  {
    id: 5,
    name: "Frankies",
    image: "",
    cuisine: "italian",
    rating: 4,
    price: "price2",
    dietary: ["shellfish"],
    website: "http://frankiesmoderndiner.com",
    description: "Frankie's is a family-friendly restaurant in Victoria, BC, dedicated to crafting diverse breakfast, lunch, and dinner menus with fresh, local ingredients and a lot of love, ensuring a delicious and inclusive dining experience for everyone.",
  }
]