export const restaurantData = [
  {
    id: 1,
    name: "Bold Butchery",
    image: "https://lh3.googleusercontent.com/gps-cs-s/AC9h4np4vV-hFaVvC0v-11iKt4QGLyZmvtQcF0WPkXciXDfkWc2Qmcz-7SnogI15snYjJvQFWsLoHt-5NxNYgUh4zC4u3_OhcpBP-30RONUXfLk1L2K2LMZZh4O_ahi3SvEw4sCu4S6qSA=s1360-w1360-h1020-rw",
    cuisine: "middle-eastern",
    rating: 4,
    price: "price2",
    dietary: ["halal", "vegetarian"],
    website: "https://www.boldshawarma.com",
    description: "Straightforward restaurant preparing shawarma & falafel wraps, plus burgers & poutine.",
  },
  {
    id: 2,
    name: "Rebar",
    image: "https://lh3.googleusercontent.com/p/AF1QipOAyI0O--AMNtVNjyJuGaf799lJO76cZIxMBe3Z=w289-h156-n-k-no",
    cuisine: "american",
    rating: 4,
    price: "price2",
    dietary: ["vegetarian", "vegan", "celiac"],
    website: "https://www.rebarfoods.com",
    description: "Rebar is a pioneering West Coast institution that has evolved from humble beginnings into a vibrant, unique dining destination known for its nourishing, health-supporting, and eclectically creative fresh food, engaging all senses from the moment you enter.",
  },
  {
    id: 3,
    name: "La Taquisa",
    image: "https://www.lataquisa.com/assets/images/tacos.jpg",
    cuisine: "mexican",
    rating: 4,
    price: "price1",
    dietary: ["peanut", "vegan", "vegetarian", "celiac"],
    website: "https://www.lataquisa.com/locations/downtown/menu/",
    description: "La Taquisa is a locally owned, family-run business combining authentic Guadalajara family recipes from Sindy with Scott's 22 years of culinary experience to offer an exceptional Mexican dining experience featuring made-from-scratch fillings, salsas, and fresh, pressed-to-order gluten-free corn tortillas.",
  },
  {
    id: 4,
    name: "MaiiZ Nixtamal Eatery & Tortilleria",
    image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2b/5a/f9/27/caption.jpg?w=900&h=500&s=1",
    cuisine: "mexican",
    rating: 5,
    price: "price2",
    dietary: ["celiac", "vegan", "vegetarian"],
    website: "https://maiiz.ca",
    description: "MAiiZ Nixtamal is a restaurant committed to providing honest, transparent food, prioritizing local farmers and organic BC-grown corn in their mission to make nixtamalized corn products more accessible. They strive for sustainability, reduce environmental impact through local sourcing, and aim to grow as a purpose-driven business while educating the community on the nutritional and cultural importance of nixtamalization.",
  },
  {
    id: 5,
    name: "Frankies",
    image: "https://resizer.otstatic.com/v3/photos/47447021-2?width=1280&height=720&webp=true",
    cuisine: "italian",
    rating: 4,
    price: "price2",
    dietary: ["vegetarian", "celiac"],
    website: "http://frankiesmoderndiner.com",
    description: "Frankie's is a family-friendly restaurant in Victoria, BC, dedicated to crafting diverse breakfast, lunch, and dinner menus with fresh, local ingredients and a lot of love, ensuring a delicious and inclusive dining experience for everyone.",
  },
{
  id: 6,
  name: "MeeT on Blanshard",
  image: "https://images.happycow.net/venues/1024/32/50/hcmp325061_1999746.jpeg",
  cuisine: "american",
  rating: 4,
  price: "price2",
  dietary: ["vegan", "vegetarian"],
  website: "https://eatmeat.ca",
  description: "MeeT is a place to gather with friends and connect over delicious food made for everyone. Our menu is 100% plant-based and features comfort classics, burgers, bowls, and more, all made from scratch.",
},
{
  id: 7,
  name: "Be Love",
  image: "https://img.cdn4dd.com/cdn-cgi/image/fit=cover,width=600,height=400,format=auto,quality=80/https://doordash-static.s3.amazonaws.com/media/store/header/49971607-4e06-4c94-bfa3-2e29866bb4d2.jpeg",
  cuisine: "american",
  rating: 5,
  price: "price2",
  dietary: ["vegan", "vegetarian", "celiac"],
  website: "https://www.beloverestaurant.ca",
  description: "Be Love is a modern restaurant serving organic, plant-based cuisine, free from gluten, dairy, and processed sugar, with a focus on nourishing, vibrant, and delicious food."
},
{
  id: 8,
  name: "Spoons Diner",
  image: "https://s3-media0.fl.yelpcdn.com/bphoto/iZm_rJXpg-aWdUo-uhH3mw/348s.jpg",
  cuisine: "american",
  rating: 4,
  price: "price2",
  dietary: ["vegetarian"],
  website: "https://spoonsdiner.com",
  description: "Spoons Diner is a funky, retro-inspired eatery serving creative takes on classic breakfast and lunch fare, with plenty of vegetarian options and locally sourced ingredients."
},
{
  id: 9,
  name: "Super Baba",
  image: "https://jewkarta.com/wp-content/uploads/2021/02/superbaba.jpg?w=1272",
  cuisine: "middle-eastern",
  rating: 4,
  price: "price1",
  dietary: ["vegan", "vegetarian"],
  website: "https://superbaba.ca",
  description: "Super Baba is a modern Middle Eastern counter-service restaurant offering fresh, flavourful wraps, plates, and salads with plenty of vegan and vegetarian options."
},
{
  id: 10,
  name: "Yates Coffee Bar",
  image: "https://images.happycow.net/venues/1024/31/20/hcmp312059_1717325.jpeg",
  cuisine: "american",
  rating: 4,
  price: "price1",
  dietary: ["vegan", "vegetarian"],
  website: "https://www.instagram.com/yatescoffeebar/?hl=en",
  description: "Yates Coffee Bar offers a variety of coffee drinks, smoothies, sandwiches, wraps, salads, and burgers, with plenty of vegan and vegetarian options available."
},
{
  id: 11,
  name: "Big Wheel Burger",
  image: "https://camosun.ca/sites/default/files/styles/responsive_1280/public/2021-08/big-wheel-burgers.jpg?itok=KqRIKimb",
  cuisine: "american",
  rating: 4,
  price: "price1",
  dietary: ["peanut", "vegetarian"],
  website: "https://bigwheelburger.com",
  description: "Big Wheel Burger serves classic burgers, fries, and shakes in a fun, fast-casual setting, and is proudly 100% peanut free with vegetarian options available."
},
{
  id: 12,
  name: "Bin 4 Burger Lounge",
  image: "https://noshandnibble.blog/content/images/2018/02/bin-4-burger-lounge-136-delizioso.jpg",
  cuisine: "american",
  rating: 4,
  price: "price2",
  dietary: ["halal", "vegetarian", "vegan", "celiac"],
  website: "https://bin4burgerlounge.com",
  description: "Bin 4 Burger Lounge serves up gourmet burgers featuring international flavours and local ingredients, with options for vegetarians, vegans, and gluten-free diets. Enjoy inventive burgers, house-made dips, and a lounge-style atmosphere."
},
{
  id: 13,
  name: "Fish on Fifth",
  image: "https://images.happycow.net/venues/1024/79/09/hcmp79094_1243693.jpeg",
  cuisine: "seafood",
  rating: 4,
  price: "price2",
  dietary: ["peanut", "vegan", "vegetarian", "celiac", "tree-nut"],
  website: "https://fishon5th.com",
  description: "Fish on Fifth is a cozy and welcoming restaurant in Sidney known for its fresh, local ingredients, standout fish and chips, extensive vegan options, and commitment to being a nut-free establishment with many gluten-free and celiac-friendly dishes."
},
{
  id: 14,
  name: "The Keg Steakhouse + Bar",
  image: "https://myvancity.ca/wp-content/uploads/2018/02/keg-feature-steak.jpg",
  cuisine: "american",
  rating: 4,
  price: "price3",
  dietary: ["celiac", "vegetarian"],
  website: "https://kegsteakhouse.com",
  description: "The Keg Steakhouse + Bar is known for its classic steak and seafood dishes served in a stylish, contemporary setting, offering vegetarian and gluten-free options to accommodate a variety of dietary preferences.",
},
{
  id: 15,
  name: "Cactus Club Cafe",
  image: "https://www.cactusclubcafe.com/wp-content/uploads/2023/10/102523_Fall-MRO_WebMenu-CategoryHeaders_750x585_TruffleParmChicken.jpg",
  cuisine: "american",
  rating: 4,
  price: "price2",
  dietary: ["vegetarian", "vegan", "celiac"],
  website: "https://www.cactusclubcafe.com/locations/victoria/",
  description: "Cactus Club Cafe offers a chef-driven menu of bold, refined dishes with something for every craving, including vegetarian, vegan, and gluten-free options, all served in a vibrant, contemporary setting in downtown Victoria.",
},
{
  id: 16,
  name: "Lotus Pond Vegetarian Restaurant",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuxyKhgpvbUhs6NCAnsJJYD7YlH2i3Bh-PBA&s",
  cuisine: "chinese",
  rating: 4,
  price: "price1",
  dietary: ["peanut", "vegan", "vegetarian"],
  website: "https://lotuspondvictoria.ca",
  description: "Lotus Pond Vegetarian Restaurant serves authentic vegan Chinese cuisine in Victoria, offering a wide variety of plant-based dishes in a welcoming, nut-free environment.",
},
{
  id: 17,
  name: "Earls Kitchen + Bar",
  image: "https://tb-static.uber.com/prod/image-proc/processed_images/bbd769bdfd768e993e6c22bbf15fbd86/885ba8620d45ab36746a0e8c7b85ee66.jpeg",
  cuisine: "american",
  rating: 4,
  price: "price2",
  dietary: ["vegetarian", "vegan", "celiac"],
  website: "https://earls.ca/locations/victoria/",
  description: "Earls Kitchen + Bar offers a diverse, globally-inspired menu with vegetarian, vegan, and gluten-free options in a vibrant, contemporary setting in downtown Victoria.",
},
{
  id: 18,
  name: "Cafe Malabar",
  image: "https://tb-static.uber.com/prod/image-proc/processed_images/efecc32cd6fe1ce9c5f5df7a303ec248/3ac2b39ad528f8c8c5dc77c59abb683d.jpeg",
  cuisine: "indian",
  rating: 4,
  price: "price2",
  dietary: ["vegan", "vegetarian"],
  website: "https://cafemalabar.ca",
  description: "Cafe Malabar brings the rich flavors of Kerala and South Indian cuisine to Victoria, offering a menu filled with traditional dishes and contemporary favorites in a welcoming setting.",
},
{
  id: 19,
  name: "Wind Cries Mary",
  image: "https://images.squarespace-cdn.com/content/v1/5f7f6ecf26b4a703afe3b79e/a30d1c78-814a-4924-b999-f0ea3ed58116/_GCP1585.jpg",
  cuisine: "american",
  rating: 4,
  price: "price3",
  dietary: ["vegetarian"],
  website: "https://www.windcriesmary.ca",
  description: "Wind Cries Mary is a stylish, rustic-chic restaurant and bar featuring locally sourced, seasonal ingredients and inventive cocktails in a lively downtown location.",
},
{
  id: 20,
  name: "Fishhook",
  image: "https://images.squarespace-cdn.com/content/v1/6042b0e049690143047f82d1/1615320359621-BJ74U0LM0RPHNCYPTEUR/Fishhook+Victoria+-+Line+%26+Sinker+01.jpg",
  cuisine: "seafood",
  rating: 4,
  price: "price2",
  dietary: ["vegetarian"],
  website: "https://fishhookvic.com",
  description: "Fishhook offers a creative menu of sustainable seafood with a fusion of Indian and French influences, served in a cozy and casual space.",
},
{
  id: 21,
  name: "Jam Cafe",
  image: "https://jamcafes.com/wp-content/plugins/phastpress/phast.php?service=images&src=https%3A%2F%2Fjamcafes.com%2Fwp-content%2Fuploads%2F2024%2F09%2Fjam-cafe-victoria-4.png&cacheMarker=1727377226-1312428&token=75aa343bd6b108db",
  cuisine: "american",
  rating: 4,
  price: "price2",
  dietary: ["vegetarian"],
  website: "https://jamcafes.com",
  description: "Jam Cafe is a bustling all-day breakfast and brunch spot known for its hearty comfort food, inventive pancakes, and welcoming atmosphere.",
},
{
  id: 22,
  name: "Pendray Inn & Teahouse",
  image: "https://image-tc.galaxy.tf/wijpeg-c0p4k5gl0sp0tiqymtkpz1gb/pendray-inn-and-tea-house-breakfast_standard.jpg?crop=107%2C0%2C1707%2C1280",
  cuisine: "british",
  rating: 4,
  price: "price3",
  dietary: ["vegetarian"],
  website: "https://www.pendrayinnandteahouse.com",
  description: "Pendray Inn & Teahouse offers a classic afternoon tea experience in a historic Victorian mansion, with beautifully presented pastries and sandwiches.",
},
{
  id: 23,
  name: "Marilena Cafe and Raw Bar",
  image: "https://admin.tourismvictoria.com/content/uploads/2023/10/Marilena-12_13June2023-CreditAllisonKuhl-5585_F671AB16-5056-A36A-0A677E54EFE4547D-f671a75d5056a36_f671b02f-5056-a36a-0a89953fa4ffcd3d.jpg",
  cuisine: "seafood",
  rating: 5,
  price: "price4",
  dietary: ["vegetarian"],
  website: "https://marilenacafe.com",
  description: "Marilena Cafe and Raw Bar features elegant, sustainable seafood and expertly crafted sushi in a refined, contemporary downtown setting.",
},
{
  id: 24,
  name: "Green Cuisine",
  image: "https://s3-media0.fl.yelpcdn.com/bphoto/rSbh-5f2_8b5hEYQEZ-C2g/348s.jpg",
  cuisine: "american",
  rating: 4,
  price: "price2",
  dietary: ["vegan", "vegetarian", "celiac"],
  website: "https://greencuisine.com",
  description: "Green Cuisine is a long-standing vegan restaurant in Victoria's Market Square, offering a diverse buffet of plant-based and gluten-free dishes in a relaxed atmosphere.",
},
{
  id: 25,
  name: "Virtuous Pie",
  image: "https://www.yammagazine.com/wp-content/uploads/2020/02/Virtuous_Pie-1024x683.jpg",
  cuisine: "italian",
  rating: 4,
  price: "price2",
  dietary: ["vegan", "vegetarian"],
  website: "https://virtuouspie.com",
  description: "Virtuous Pie is a modern eatery specializing in innovative plant-based pizzas and house-made vegan ice cream.",
},
{
  id: 26,
  name: "Fern Cafe and Bakery",
  image: "https://img.cdn4dd.com/cdn-cgi/image/fit=cover,width=600,height=400,format=auto,quality=80/https://doordash-static.s3.amazonaws.com/media/store/header/551f8fde-c691-4c0a-898b-345dae751a2a.jpg",
  cuisine: "american",
  rating: 4,
  price: "price1",
  dietary: ["vegan", "vegetarian"],
  website: "https://ferncafeandbakery.ca",
  description: "Fern Cafe and Bakery is Victoria's first all-vegan cafe and bakery, serving comfort food, sandwiches, and a variety of baked treats.",
},
{
  id: 27,
  name: "The Very Good Butchers",
  image: "https://www.vkind.com/wp-content/uploads/2021/10/TheVeryGoodButchers.jpg",
  cuisine: "american",
  rating: 4,
  price: "price2",
  dietary: ["vegan", "vegetarian"],
  website: "https://www.verygoodbutchers.com",
  description: "The Very Good Butchers craft delicious plant-based meats and serve vegan comfort food in Victoria Public Market.",
},
{
  id: 28,
  name: "Red Fish Blue Fish",
  image: "https://images.squarespace-cdn.com/content/v1/5693335a05f8e207078c4bc5/1590520563516-DYFB3NNZVIF5MY7S8W3D/image-asset.jpeg",
  cuisine: "seafood",
  rating: 4,
  price: "price1",
  dietary: ["celiac"],
  website: "https://www.redfish-bluefish.com",
  description: "Red Fish Blue Fish is a dockside eatery housed in a repurposed shipping container, serving up sustainable, Ocean Wise seafood with stunning views of Victoria’s Inner Harbour.",
},
{
  id: 29,
  name: "Nubo Japanese Tapas",
  image: "https://images.squarespace-cdn.com/content/v1/5710267fc2ea5128296569f5/1597814382596-35F3E5AMT0V38UEF0RYB/edit..IMG_0105.jpg",
  cuisine: "japanese",
  rating: 4,
  price: "price2",
  dietary: ["celiac", "vegetarian"],
  website: "https://nubotapas.com",
  description: "Nubo Japanese Tapas offers a creative selection of Japanese small plates and sushi in a lively, modern setting.",
},
{
  id: 30,
  name: "Masala Bites",
  image: "https://img.p.mapq.st/?url=https://ir.4sqi.net/img/general/original/21150772_C4B7E9FQwdkyRNZaa8c8c-GxE-VGwg6NQ5ubRvKwD3I.jpg?w=3840&q=75",
  cuisine: "indian",
  rating: 4,
  price: "price2",
  dietary: ["halal", "vegan", "vegetarian", "celiac"],
  website: "https://masalabites.ca",
  description: "Masala Bites brings the vibrant flavors of Indian cuisine to Victoria, featuring a diverse menu of traditional dishes and contemporary favorites.",
},
{
  id: 31,
  name: "The Village Restaurant",
  image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/22/8c/1c/the-village-restaurant.jpg?w=900&h=500&s=1",
  cuisine: "american",
  rating: 4,
  price: "price2",
  dietary: ["celiac", "vegetarian"],
  website: "https://thevillagerestaurant.ca",
  description: "The Village is a community-focused breakfast and brunch spot known for its welcoming atmosphere and locally sourced ingredients.",
},
{
  id: 32,
  name: "Little Thai Place",
  image: "https://img.cdn4dd.com/cdn-cgi/image/fit=cover,width=600,height=400,format=auto,quality=80/https://doordash-static.s3.amazonaws.com/media/store/header/57693b28-dfa7-4034-b34e-484a00760eb1.jpg",
  cuisine: "thai",
  rating: 4,
  price: "price1",
  dietary: ["celiac", "vegan", "vegetarian"],
  website: "https://littlethaiplace.com",
  description: "Little Thai Place is a local favorite offering authentic Thai cuisine with fresh ingredients and bold flavors.",
},
{
  id: 33,
  name: "Sizzling Tandoor",
  image: "https://tb-static.uber.com/prod/image-proc/processed_images/48ef6706018c56b284ed8f354fbd1c55/8a42ee7a692dfa4155879820804a277f.jpeg",
  cuisine: "indian",
  rating: 4,
  price: "price2",
  dietary: ["halal", "vegan", "vegetarian", "celiac"],
  website: "https://sizzlingtandoor.ca",
  description: "Sizzling Tandoor is celebrated for its classic North Indian dishes, vibrant spices, and warm hospitality.",
},
{
  id: 34,
  name: "Tacofino",
  image: "https://www.tacofino.com/img/ordering/img-ordering-1-alt-2.jpg",
  cuisine: "mexican",
  rating: 4,
  price: "price1",
  dietary: ["celiac", "vegetarian"],
  website: "https://tacofino.com",
  description: "Tacofino serves up West Coast-inspired Mexican fare in a fun and casual atmosphere, famous for its tacos and burritos.",
},
{
  id: 35,
  name: "Baan Thai Wok & Bar",
  image: "https://dbef6nccyyyig.cloudfront.net/app/uploads/2022/08/untitled-3798-1920x878.jpg",
  cuisine: "thai",
  rating: 4,
  price: "price2",
  dietary: ["celiac", "vegan", "vegetarian"],
  website: "https://baanthaivictoria.ca",
  description: "Baan Thai Wok & Bar offers a welcoming setting and a menu filled with classic Thai dishes made from scratch.",
},
{
  id: 36,
  name: "Nourish Kitchen & Cafe",
  image: "https://images.squarespace-cdn.com/content/v1/59bad0bf18b27d192cee0bd1/1576468470219-6WHF29V9QXMWXKXPBJC9/IMG_4739.jpg?format=500w",
  cuisine: "american",
  rating: 4,
  price: "price2",
  dietary: ["vegan", "vegetarian", "celiac"],
  website: "https://nourishkitchen.ca",
  description: "Nourish Kitchen & Cafe is set in a charming heritage house and offers a creative, health-focused menu using local and organic ingredients, with plenty of gluten-free, vegan, and vegetarian options.",
},
{
  id: 37,
  name: "Turmeric Indian Cuisine",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaEq000ZMFkmNmsQZt4RqD60lnThbowIbZYg&s",
  cuisine: "indian",
  rating: 4,
  price: "price2",
  dietary: ["halal", "vegan", "vegetarian", "celiac"],
  website: "https://turmericvictoria.com",
  description: "Turmeric Indian Cuisine offers a wide range of traditional Indian dishes in a contemporary space, with an emphasis on fresh ingredients and bold flavors.",
},
{
  id: 38,
  name: "Agrius Restaurant",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4OF4vJ8ZY083C8LhTui-p8RDl2lxxLQ_DCA&s",
  cuisine: "french",
  rating: 4,
  price: "price3",
  dietary: ["vegan", "vegetarian", "celiac"],
  website: "https://agrius.ca",
  description: "Agrius Restaurant is known for its locally sourced, organic menu inspired by French cuisine, offering creative dishes with vegan, vegetarian, and gluten-free options in a modern setting.",
},
{
  id: 39,
  name: "Part and Parcel",
  image: "https://tb-static.uber.com/prod/image-proc/processed_images/d09cb56807e9e29988b94fd47b2eea3f/3ac2b39ad528f8c8c5dc77c59abb683d.jpeg",
  cuisine: "american",
  rating: 4,
  price: "price2",
  dietary: ["vegan", "vegetarian", "celiac"],
  website: "https://www.partandparcel.ca",
  description: "Part and Parcel is a cozy, counter-service eatery offering locally sourced, globally inspired dishes with a focus on fresh, seasonal ingredients and a variety of vegan, vegetarian, and gluten-free options.",
},
{
  id: 40,
  name: "Yua Japanese Bistro",
  image: "https://tb-static.uber.com/prod/image-proc/processed_images/6b6d14de217db6b4b2133b06f72608b2/30be7d11a3ed6f6183354d1933fbb6c7.jpeg",
  cuisine: "japanese",
  rating: 4,
  price: "price2",
  dietary: ["celiac", "vegetarian"],
  website: "https://yuabistro.com",
  description: "Yua Japanese Bistro features a modern menu of sushi, sashimi, and Japanese small plates, with a focus on fresh ingredients and artistic presentation.",
},
{
  id: 41,
  name: "Nautical Nellies",
  image: "https://img.cdn4dd.com/cdn-cgi/image/fit=cover,width=600,height=400,format=auto,quality=80/https://doordash-static.s3.amazonaws.com/media/store/header/518cf897-4805-4bcb-a963-562f74c74915.jpg",
  cuisine: "seafood",
  rating: 4,
  price: "price3",
  dietary: ["celiac", "vegetarian"],
  website: "https://nauticalnelliesrestaurant.com",
  description: "Nautical Nellies is a waterfront steak and seafood restaurant in downtown Victoria, known for its fresh local seafood, premium steaks, and extensive wine list.",
},
{
  id: 42,
  name: "Pho Vy",
  image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/07/86/0c/ae/pho-vy.jpg?w=900&h=500&s=1",
  cuisine: "vietnamese",
  rating: 4,
  price: "price1",
  dietary: ["celiac", "vegetarian"],
  website: "https://www.instagram.com/explore/locations/173209/pho-vy-vietnamese-restaurant/?hl=en",
  description: "Pho Vy is a family-run Vietnamese restaurant offering traditional pho, noodle bowls, and authentic Vietnamese specialties in a relaxed, friendly space.",
},
{
  id: 43,
  name: "Sen Zushi",
  image: "https://senzushi.com/sites/default/files/styles/webp/public/2024-10/xtraditional-nigiri-Japanese-cuisine-sen-zushi.jpg.webp,qitok=090nrBRb.pagespeed.ic.qusBmtJ86E.webp",
  cuisine: "japanese",
  rating: 4,
  price: "price2",
  dietary: ["celiac", "vegetarian"],
  website: "https://senzushi.com",
  description: "Sen Zushi is a well-loved spot for authentic Japanese cuisine, featuring expertly prepared sushi, sashimi, and Japanese comfort food in a warm, inviting atmosphere.",
},
{
  id: 44,
  name: "Varsha Indian Kitchen",
  image: "https://images.squarespace-cdn.com/content/v1/53b485f4e4b0d06a988f3900/1610081439559-YM9GR18V8QM2EDFB7XDC/curries+1.jpg",
  cuisine: "indian",
  rating: 4,
  price: "price2",
  dietary: ["halal", "vegan", "vegetarian", "celiac"],
  website: "https://varsha.ca",
  description: "Varsha Indian Kitchen offers a modern twist on classic Indian dishes, blending traditional spices with local ingredients in a stylish, contemporary space.",
},
{
  id: 45,
  name: "Sushi Story",
  image: "https://s3-media0.fl.yelpcdn.com/bphoto/uAPIDSdhPJM4LAJjtGkTpQ/348s.jpg",
  cuisine: "japanese",
  rating: 4,
  price: "price1",
  dietary: ["celiac", "vegetarian"],
  website: "https://sushi-story.ca",
  description: "Sushi Story is a cozy Japanese eatery known for its fresh sushi, creative rolls, and friendly service.",
},
{
  id: 46,
  name: "Shizen Japanese Restaurant",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKioUU_ZpsEBoad2lr_x63ryxwSudcoXStNQ&s",
  cuisine: "japanese",
  rating: 4,
  price: "price2",
  dietary: ["celiac", "vegetarian"],
  website: "https://shizensushi.ca",
  description: "Shizen Japanese Restaurant serves a wide variety of sushi, sashimi, and traditional Japanese dishes in a welcoming, relaxed setting.",
},
{
  id: 47,
  name: "Sabhai Thai",
  image: "https://sabhai.ca/wp-content/uploads/2013/09/blog-feature-website.jpg",
  cuisine: "thai",
  rating: 4,
  price: "price2",
  dietary: ["vegan", "vegetarian", "celiac"],
  website: "https://sabhai.ca",
  description: "Sabhai Thai is a popular destination for classic Thai cuisine, offering a menu of flavorful curries, noodles, and stir-fries in a warm, inviting environment.",
},
{
  id: 48,
  name: "Kuma Noodle Japan",
  image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/10/6d/72/16/photo2jpg.jpg?w=900&h=500&s=1",
  cuisine: "japanese",
  rating: 4,
  price: "price1",
  dietary: ["vegetarian"],
  website: "https://www.instagram.com/explore/locations/6989663/kuma-noodle-japan/",
  description: "Kuma Noodle Japan is a ramen shop specializing in hearty, comforting bowls of ramen and Japanese favorites with vegetarian options.",
},
{
  id: 49,
  name: "The Blue Nile",
  image: "https://www.skipthedishes.com/_next/image?url=https%3A%2F%2Fstatic.skipthedishes.com%2Fthe-blue-nile-african-restaurant-victoria-menu-image-large-1487265039650.jpg&w=3840&q=75",
  cuisine: "middle-eastern",
  rating: 4,
  price: "price2",
  dietary: ["vegan", "vegetarian", "celiac"],
  website: "https://bluenilerestaurant.ca",
  description: "The Blue Nile serves authentic Ethiopian cuisine, including injera and richly spiced stews, in a cozy, family-run setting.",
},
{
  id: 50,
  name: "The Tapa Bar",
  image: "https://i0.wp.com/tapabar.ca/wp-content/uploads/2022/06/Tostada-n-Others-scaled.jpg?resize=300%2C300&ssl=1",
  cuisine: "american",
  rating: 4,
  price: "price2",
  dietary: ["vegan", "vegetarian", "celiac"],
  website: "https://tapabar.ca",
  description: "The Tapa Bar is a lively downtown restaurant offering Spanish-inspired tapas, wood-fired pizzas, and creative cocktails in a vibrant setting.",
},
]